In [34]:
!pip install pydotplus

Collecting pydotplus
  Downloading pydotplus-2.0.2.tar.gz (278 kB)
Requirement already satisfied: pyparsing>=2.0.1 in c:\users\win 10\anaconda3\lib\site-packages (from pydotplus) (3.0.4)
Building wheels for collected packages: pydotplus
  Building wheel for pydotplus (setup.py): started
  Building wheel for pydotplus (setup.py): finished with status 'done'
  Created wheel for pydotplus: filename=pydotplus-2.0.2-py3-none-any.whl size=24575 sha256=32dbd3e17fd063e7e05cb98ac5a2464202ed5a4d6c14b4c3a660b0bad9c43496
  Stored in directory: c:\users\win 10\appdata\local\pip\cache\wheels\89\e5\de\6966007cf223872eedfbebbe0e074534e72e9128c8fd4b55eb
Successfully built pydotplus
Installing collected packages: pydotplus
Successfully installed pydotplus-2.0.2

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier as RF
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.tree import export_graphviz
from six import StringIO
import pydotplus

In [3]:
fraud = pd.read_csv('Fraud_check.csv')

In [4]:
fraud

,Undergrad,Marital.Status,Taxable.Income,City.Population,Work.Experience,Urban
0,NO,Single,68833,50047,10,YES
1,YES,Divorced,33700,134075,18,YES
2,NO,Married,36925,160205,30,YES
3,YES,Single,50190,193264,15,YES
4,NO,Married,81002,27533,28,NO
...,...,...,...,...,...,...
595,YES,Divorced,76340,39492,7,YES
596,YES,Divorced,69967,55369,2,YES
597,NO,Divorced,47334,154058,0,YES
598,YES,Married,98592,180083,17,NO
599,NO,Divorced,96519,158137,16,NO

## EDA

In [5]:
fraud["income"]="<=30000"
fraud.loc[fraud["Taxable.Income"]>=30000,"income"]="Good"
fraud.loc[fraud["Taxable.Income"]<=30000,"income"]="Risky"

In [7]:
fraud['income'].value_counts()

Good     476
Risky    124
Name: income, dtype: int64

In [8]:
fraud.drop(["Taxable.Income"],axis=1,inplace=True)
fraud.rename(columns={"Undergrad":"undergrad","Marital.Status":"marital","City.Population":"population","Work.Experience":"experience","Urban":"urban"},inplace=True)

In [9]:
fraud

    undergrad   marital  population  experience urban income
0          NO    Single       50047          10   YES   Good
1         YES  Divorced      134075          18   YES   Good
2          NO   Married      160205          30   YES   Good
3         YES    Single      193264          15   YES   Good
4          NO   Married       27533          28    NO   Good
..        ...       ...         ...         ...   ...    ...
595       YES  Divorced       39492           7   YES   Good
596       YES  Divorced       55369           2   YES   Good
597        NO  Divorced      154058           0   YES   Good
598       YES   Married      180083          17    NO   Good
599        NO  Divorced      158137          16    NO   Good

[600 rows x 6 columns]

In [10]:
fraud.dtypes

undergrad     object
marital       object
population     int64
experience     int64
urban         object
income        object
dtype: object

In [11]:
fraud['undergrad'].value_counts()

YES    312
NO     288
Name: undergrad, dtype: int64

In [12]:
fraud['marital'].value_counts()

Single      217
Married     194
Divorced    189
Name: marital, dtype: int64

In [13]:
fraud['urban'].value_counts()

YES    302
NO     298
Name: urban, dtype: int64

## Getting Dummies

In [14]:
fraud=pd.get_dummies(fraud,columns=['undergrad','marital','urban'], drop_first=True)

In [16]:
fraud.dtypes

population          int64
experience          int64
income             object
undergrad_YES       uint8
marital_Married     uint8
marital_Single      uint8
urban_YES           uint8
dtype: object

In [17]:
fraud

,population,experience,income,undergrad_YES,marital_Married,marital_Single,urban_YES
0,50047,10,Good,0,0,1,1
1,134075,18,Good,1,0,0,1
2,160205,30,Good,0,1,0,1
3,193264,15,Good,1,0,1,1
4,27533,28,Good,0,1,0,0
...,...,...,...,...,...,...,...
595,39492,7,Good,1,0,0,1
596,55369,2,Good,1,0,0,1
597,154058,0,Good,0,0,0,1
598,180083,17,Good,1,1,0,0
599,158137,16,Good,0,0,0,0

In [19]:
x_1=fraud.drop('income',axis=1)
y_1=fraud['income']

In [20]:
x_1

,population,experience,undergrad_YES,marital_Married,marital_Single,urban_YES
0,50047,10,0,0,1,1
1,134075,18,1,0,0,1
2,160205,30,0,1,0,1
3,193264,15,1,0,1,1
4,27533,28,0,1,0,0
...,...,...,...,...,...,...
595,39492,7,1,0,0,1
596,55369,2,1,0,0,1
597,154058,0,0,0,0,1
598,180083,17,1,1,0,0
599,158137,16,0,0,0,0

In [21]:
y_1

0      Good
1      Good
2      Good
3      Good
4      Good
       ...
595    Good
596    Good
597    Good
598    Good
599    Good
Name: income, Length: 600, dtype: object

In [23]:
from sklearn.preprocessing import LabelEncoder
le= LabelEncoder()
y= le.fit_transform(y_1)

## Normalising Data

In [24]:
def norm_func(i):
    x = (i-i.min())/(i.max()-i.min())
    return (x)

In [25]:
x= norm_func(x_1)

In [26]:
x

,population,experience,undergrad_YES,marital_Married,marital_Single,urban_YES
0,0.139472,0.333333,0.0,0.0,1.0,1.0
1,0.622394,0.600000,1.0,0.0,0.0,1.0
2,0.772568,1.000000,0.0,1.0,0.0,1.0
3,0.962563,0.500000,1.0,0.0,1.0,1.0
4,0.010081,0.933333,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...
595,0.078811,0.233333,1.0,0.0,0.0,1.0
596,0.170058,0.066667,1.0,0.0,0.0,1.0
597,0.737240,0.000000,0.0,0.0,0.0,1.0
598,0.886810,0.566667,1.0,1.0,0.0,0.0
599,0.760683,0.533333,0.0,0.0,0.0,0.0

In [28]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,stratify = y) #spliting data in test and train

## Model

In [29]:
model = RF(n_jobs = 3,n_estimators = 15, oob_score = True, criterion = "entropy")
model.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy', n_estimators=15, n_jobs=3,
                       oob_score=True)

In [30]:
model.estimators_

[DecisionTreeClassifier(criterion='entropy', max_features='sqrt',
                        random_state=2134937688),
 DecisionTreeClassifier(criterion='entropy', max_features='sqrt',
                        random_state=1131698298),
 DecisionTreeClassifier(criterion='entropy', max_features='sqrt',
                        random_state=623982084),
 DecisionTreeClassifier(criterion='entropy', max_features='sqrt',
                        random_state=99263678),
 DecisionTreeClassifier(criterion='entropy', max_features='sqrt',
                        random_state=2095791869),
 DecisionTreeClassifier(criterion='entropy', max_features='sqrt',
                        random_state=588882162),
 DecisionTreeClassifier(criterion='entropy', max_features='sqrt',
                        random_state=620305547),
 DecisionTreeClassifier(criterion='entropy', max_features='sqrt',
                        random_state=380021782),
 DecisionTreeClassifier(criterion='entropy', max_features='sqrt',
                        random_state=1240276729),
 DecisionTreeClassifier(criterion='entropy', max_features='sqrt',
                        random_state=1185691375),
 DecisionTreeClassifier(criterion='entropy', max_features='sqrt',
                        random_state=563999477),
 DecisionTreeClassifier(criterion='entropy', max_features='sqrt',
                        random_state=2040344929),
 DecisionTreeClassifier(criterion='entropy', max_features='sqrt',
                        random_state=2048215311),
 DecisionTreeClassifier(criterion='entropy', max_features='sqrt',
                        random_state=894361671),
 DecisionTreeClassifier(criterion='entropy', max_features='sqrt',
                        random_state=1995509418)]

In [31]:
model.classes_

array([0, 1])

In [32]:
model.n_classes_

2

In [33]:
model.n_outputs_

1

In [34]:
model.oob_score_

0.7333333333333333

# Prediction

In [35]:
##Prediction on test data
pred_test = model.predict(x_test)

In [62]:
##Accuracy
acc_test =accuracy_score(y_test,pred_test)
print(acc_test)

0.7083333333333334

In [49]:
feature_names= x.columns
target_names=np.array(["Good","Risky"])

In [72]:
## In random forest we can plot a Decision tree present in Random forest


tree = model.estimators_[5]

dot_data = StringIO()
export_graphviz(tree,out_file = dot_data, filled = True,rounded = True, feature_names = x.columns ,class_names =target_names,impurity =False)

graph = pydotplus.graph_from_dot_data(dot_data.getvalue())

### Creating pdf and png file the selected decision tree

In [71]:

graph.write_pdf('fraudrf.pdf')
graph.write_png('fraudrf.png')

InvocationException: GraphViz's executables not found

In [64]:
graph = pydotplus.graph_from_dot_data(dot_data.getvalue())
graph.write_pdf("iris.pdf")

InvocationException: GraphViz's executables not found